"""add likely_image_only to pdfmetadata

Revision ID: 2b8bebd8cdf1
Revises: f1e4fa5f775c
Create Date: 2026-08-14 12:55:54.650814

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2b8bebd8cdf1"
down_revision: str | Sequence[str] | None = "f1e4fa5f775c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pdfmetadata", schema=None) as batch_op:
        batch_op.add_column(sa.Column("likely_image_only", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pdfmetadata", schema=None) as batch_op:
        batch_op.drop_column("likely_image_only")

    # ### end Alembic commands ###
