"""add product_id fk to entry

Revision ID: 454ae90a7155
Revises: f27fa1d64492
Create Date: 2026-07-28 13:41:49.691784

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

import rpg_librarian_mcp.model.core

# revision identifiers, used by Alembic.
revision: str = "454ae90a7155"
down_revision: str | Sequence[str] | None = "f27fa1d64492"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", rpg_librarian_mcp.model.core.UTCDateTime(), nullable=False
        ),
        sa.Column(
            "updated_at", rpg_librarian_mcp.model.core.UTCDateTime(), nullable=False
        ),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("artists", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("publisher", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("year", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("entry", schema=None) as batch_op:
        batch_op.add_column(sa.Column("product_id", sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(
            "fk_entry_product_id_product", "product", ["product_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("entry", schema=None) as batch_op:
        batch_op.drop_constraint("fk_entry_product_id_product", type_="foreignkey")
        batch_op.drop_column("product_id")

    op.drop_table("product")
    # ### end Alembic commands ###
