"""add metadata tables, product system and identification_method

Revision ID: 7a9aef9f14b2
Revises: 598a34c6ad5b
Create Date: 2026-07-28 19:32:26.318598

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

import rpg_librarian_mcp.model.core

# revision identifiers, used by Alembic.
revision: str = "7a9aef9f14b2"
down_revision: str | Sequence[str] | None = "598a34c6ad5b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audiometadata",
        sa.Column("entry_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", rpg_librarian_mcp.model.core.UTCDateTime(), nullable=False
        ),
        sa.Column(
            "updated_at", rpg_librarian_mcp.model.core.UTCDateTime(), nullable=False
        ),
        sa.Column("genre", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["entry_id"], ["entry.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("entry_id"),
    )
    op.create_table(
        "filemetadata",
        sa.Column("entry_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", rpg_librarian_mcp.model.core.UTCDateTime(), nullable=False
        ),
        sa.Column(
            "updated_at", rpg_librarian_mcp.model.core.UTCDateTime(), nullable=False
        ),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("artist", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("publisher", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("copyright", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(["entry_id"], ["entry.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("entry_id"),
    )
    op.create_table(
        "imagemetadata",
        sa.Column("entry_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", rpg_librarian_mcp.model.core.UTCDateTime(), nullable=False
        ),
        sa.Column(
            "updated_at", rpg_librarian_mcp.model.core.UTCDateTime(), nullable=False
        ),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("has_alpha", sa.Boolean(), nullable=True),
        sa.Column("pixel_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["entry_id"], ["entry.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("entry_id"),
    )
    op.create_table(
        "meshmetadata",
        sa.Column("entry_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", rpg_librarian_mcp.model.core.UTCDateTime(), nullable=False
        ),
        sa.Column(
            "updated_at", rpg_librarian_mcp.model.core.UTCDateTime(), nullable=False
        ),
        sa.Column("bounding_box_x", sa.Float(), nullable=True),
        sa.Column("bounding_box_y", sa.Float(), nullable=True),
        sa.Column("bounding_box_z", sa.Float(), nullable=True),
        sa.Column("surface_area", sa.Float(), nullable=True),
        sa.Column(
            "unit",
            sa.Enum("mm", "cm", "m", "inch", "ft", name="lengthunit"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["entry_id"], ["entry.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("entry_id"),
    )
    op.create_table(
        "pdfmetadata",
        sa.Column("entry_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", rpg_librarian_mcp.model.core.UTCDateTime(), nullable=False
        ),
        sa.Column(
            "updated_at", rpg_librarian_mcp.model.core.UTCDateTime(), nullable=False
        ),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("is_encrypted", sa.Boolean(), nullable=True),
        sa.Column("needs_password", sa.Boolean(), nullable=True),
        sa.Column("has_extractable_text", sa.Boolean(), nullable=True),
        sa.Column("likely_scanned", sa.Boolean(), nullable=True),
        sa.Column("barcode", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("isbn", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("issn", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sampled_text", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(["entry_id"], ["entry.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("entry_id"),
    )
    op.create_table(
        "videometadata",
        sa.Column("entry_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", rpg_librarian_mcp.model.core.UTCDateTime(), nullable=False
        ),
        sa.Column(
            "updated_at", rpg_librarian_mcp.model.core.UTCDateTime(), nullable=False
        ),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("has_audio", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["entry_id"], ["entry.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("entry_id"),
    )
    with op.batch_alter_table("product", schema=None) as batch_op:
        # server_default backfills existing rows; identification_method's is
        # dropped below since new rows should always set it explicitly --
        # 'manual' only describes pre-existing rows created before this
        # column existed.
        batch_op.add_column(
            sa.Column(
                "system",
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=False,
                server_default="unknown",
            )
        )
        batch_op.add_column(
            sa.Column(
                "identification_method",
                sa.Enum(
                    "isbn_match",
                    "rpggeek_match",
                    "drivethru_match",
                    "filename_heuristic",
                    "llm_judgment",
                    "manual",
                    name="identificationmethod",
                ),
                nullable=False,
                server_default="manual",
            )
        )
        batch_op.alter_column("title", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("description", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("artists", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("publisher", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("year", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.create_index(
            batch_op.f("ix_product_identification_method"),
            ["identification_method"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_product_system"), ["system"], unique=False)

    # Drop the backfill default now that existing rows are covered -- new
    # rows should always set identification_method explicitly.
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.alter_column("identification_method", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_product_system"))
        batch_op.drop_index(batch_op.f("ix_product_identification_method"))
        batch_op.alter_column("year", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("publisher", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("artists", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("description", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("title", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.drop_column("identification_method")
        batch_op.drop_column("system")

    op.drop_table("videometadata")
    op.drop_table("pdfmetadata")
    op.drop_table("meshmetadata")
    op.drop_table("imagemetadata")
    op.drop_table("filemetadata")
    op.drop_table("audiometadata")
    # ### end Alembic commands ###
