"""create entry and error tables

Revision ID: a0982134c448
Revises:
Create Date: 2026-07-24 16:20:13.475840

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

import rpg_librarian_mcp.model.core

# revision identifiers, used by Alembic.
revision: str = "a0982134c448"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entry",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column(
            "parent_path",
            rpg_librarian_mcp.model.core.ParentPathType(length=1024),
            nullable=False,
        ),
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sha356", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("size_in_bytes", sa.Integer(), nullable=False),
        sa.Column("mime_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "media_type",
            sa.Enum(
                "audio",
                "video",
                "image",
                "vector",
                "pdf",
                "mesh",
                "text",
                "unknown",
                name="mediatype",
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("parent_path", "filename"),
    )
    with op.batch_alter_table("entry", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_entry_media_type"), ["media_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_entry_parent_path"), ["parent_path"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_entry_sha356"), ["sha356"], unique=False)

    op.create_table(
        "error",
        sa.Column("entry_id", sa.Uuid(), nullable=False),
        sa.Column("stage", sa.String(), nullable=False),
        sa.Column("error_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["entry_id"], ["entry.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("entry_id", "stage"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("error")
    with op.batch_alter_table("entry", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_entry_sha356"))
        batch_op.drop_index(batch_op.f("ix_entry_parent_path"))
        batch_op.drop_index(batch_op.f("ix_entry_media_type"))

    op.drop_table("entry")
    # ### end Alembic commands ###
