"""add review flag table

Revision ID: f1e4fa5f775c
Revises: 06f71334c29a
Create Date: 2026-07-31 10:13:04.025916

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

import rpg_librarian_mcp.model.core

# revision identifiers, used by Alembic.
revision: str = "f1e4fa5f775c"
down_revision: str | Sequence[str] | None = "06f71334c29a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reviewflag",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", rpg_librarian_mcp.model.core.UTCDateTime(), nullable=False
        ),
        sa.Column(
            "updated_at", rpg_librarian_mcp.model.core.UTCDateTime(), nullable=False
        ),
        sa.Column("entry_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "resolved_at", rpg_librarian_mcp.model.core.UTCDateTime(), nullable=True
        ),
        sa.Column("resolution_note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(["entry_id"], ["entry.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reviewflag", schema=None) as batch_op:
        batch_op.create_index(
            "ix_reviewflag_open_entry_id",
            ["entry_id"],
            unique=True,
            sqlite_where=sa.text("resolved_at IS NULL"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reviewflag", schema=None) as batch_op:
        batch_op.drop_index(
            "ix_reviewflag_open_entry_id", sqlite_where=sa.text("resolved_at IS NULL")
        )

    op.drop_table("reviewflag")
    # ### end Alembic commands ###
