"""add content_role to product

Revision ID: 06f71334c29a
Revises: 592aeb22d8d0
Create Date: 2026-07-30 22:39:10.143563

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "06f71334c29a"
down_revision: str | Sequence[str] | None = "592aeb22d8d0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "content_role",
                sa.Enum(
                    "core_rules",
                    "adventures_and_scenarios",
                    "settings_and_supplements",
                    "gm_and_player_aids",
                    "extras",
                    name="contentrole",
                ),
                nullable=True,
            )
        )
        batch_op.create_index(
            batch_op.f("ix_product_content_role"), ["content_role"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_product_content_role"))
        batch_op.drop_column("content_role")

    # ### end Alembic commands ###
