"""add pdfcontents table, drop legacy columns from pdfmetadata

Revision ID: 592aeb22d8d0
Revises: 7a9aef9f14b2
Create Date: 2026-07-30 11:49:40.470693

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

import rpg_librarian_mcp.model.core

# revision identifiers, used by Alembic.
revision: str = "592aeb22d8d0"
down_revision: str | Sequence[str] | None = "7a9aef9f14b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pdfcontents",
        sa.Column("entry_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", rpg_librarian_mcp.model.core.UTCDateTime(), nullable=False
        ),
        sa.Column(
            "updated_at", rpg_librarian_mcp.model.core.UTCDateTime(), nullable=False
        ),
        sa.Column("barcode", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("isbn", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("issn", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sample_text", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("possible_system", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(["entry_id"], ["entry.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("entry_id"),
    )
    with op.batch_alter_table("pdfmetadata", schema=None) as batch_op:
        batch_op.drop_column("barcode")
        batch_op.drop_column("sampled_text")
        batch_op.drop_column("isbn")
        batch_op.drop_column("issn")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pdfmetadata", schema=None) as batch_op:
        batch_op.add_column(sa.Column("issn", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("isbn", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("sampled_text", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("barcode", sa.VARCHAR(), nullable=True))

    op.drop_table("pdfcontents")
    # ### end Alembic commands ###
