"""initial catalog

Revision ID: 0001
Revises:
Create Date: 2026-09-19 20:26:55.941155

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "root",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("last_scanned_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("path"),
    )
    with op.batch_alter_table("root", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_root_kind"), ["kind"], unique=False)

    op.create_table(
        "product_line",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("product_type_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_type_id"],
            ["product_type.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_type_id", "name"),
    )
    with op.batch_alter_table("product_line", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_product_line_product_type_id"),
            ["product_type_id"],
            unique=False,
        )

    op.create_table(
        "product",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("product_line_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("publisher", sa.String(), nullable=True),
        sa.Column("year", sa.String(), nullable=True),
        sa.Column("artists", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_line_id"],
            ["product_line.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_line_id", "name"),
    )
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_product_product_line_id"), ["product_line_id"], unique=False
        )

    op.create_table(
        "product_line_alias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("product_line_id", sa.Integer(), nullable=False),
        sa.Column("alias", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_line_id"], ["product_line.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_line_id", "alias"),
    )
    with op.batch_alter_table("product_line_alias", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_product_line_alias_product_line_id"),
            ["product_line_id"],
            unique=False,
        )

    op.create_table(
        "file",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("root_id", sa.Integer(), nullable=False),
        sa.Column("relative_path", sa.String(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("mtime", sa.Integer(), nullable=False),
        sa.Column("mime_type", sa.String(), nullable=True),
        sa.Column("media_type", sa.String(length=32), nullable=True),
        sa.Column("sha256", sa.String(), nullable=True),
        sa.Column(
            "disposition",
            sa.String(length=16),
            server_default="unfiled",
            nullable=False,
        ),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("duplicate_of_id", sa.Integer(), nullable=True),
        sa.Column("missing_since", sa.DateTime(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "disposition != 'keep' OR product_id IS NOT NULL",
            name="ck_file_keep_requires_product",
        ),
        sa.ForeignKeyConstraint(["duplicate_of_id"], ["file.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["root_id"],
            ["root.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("root_id", "relative_path"),
    )
    with op.batch_alter_table("file", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_file_disposition"), ["disposition"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_file_duplicate_of_id"), ["duplicate_of_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_file_media_type"), ["media_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_file_product_id"), ["product_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_file_root_id"), ["root_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_file_sha256"), ["sha256"], unique=False)

    op.create_table(
        "audio_metadata",
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("genre", sa.String(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["file_id"], ["file.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("file_id"),
    )
    op.create_table(
        "error",
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("error_text", sa.String(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["file_id"], ["file.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("file_id", "stage"),
    )
    op.create_table(
        "file_llm_extraction",
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("possible_system", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["file_id"], ["file.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("file_id"),
    )
    op.create_table(
        "file_metadata",
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("artist", sa.String(), nullable=True),
        sa.Column("publisher", sa.String(), nullable=True),
        sa.Column("copyright", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["file_id"], ["file.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("file_id"),
    )
    op.create_table(
        "file_text",
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("barcode", sa.String(), nullable=True),
        sa.Column("isbn", sa.String(), nullable=True),
        sa.Column("issn", sa.String(), nullable=True),
        sa.Column("sample_pages", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["file_id"], ["file.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("file_id"),
    )
    with op.batch_alter_table("file_text", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_file_text_isbn"), ["isbn"], unique=False)
        batch_op.create_index(batch_op.f("ix_file_text_issn"), ["issn"], unique=False)

    op.create_table(
        "image_metadata",
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("has_alpha", sa.Boolean(), nullable=True),
        sa.Column("pixel_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["file_id"], ["file.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("file_id"),
    )
    with op.batch_alter_table("image_metadata", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_image_metadata_pixel_count"), ["pixel_count"], unique=False
        )

    op.create_table(
        "mesh_metadata",
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("bounding_box_x", sa.Float(), nullable=True),
        sa.Column("bounding_box_y", sa.Float(), nullable=True),
        sa.Column("bounding_box_z", sa.Float(), nullable=True),
        sa.Column("surface_area", sa.Float(), nullable=True),
        sa.Column(
            "unit",
            sa.Enum("mm", "cm", "m", "inch", "ft", name="lengthunit"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["file_id"], ["file.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("file_id"),
    )
    op.create_table(
        "pdf_metadata",
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("is_encrypted", sa.Boolean(), nullable=True),
        sa.Column("needs_password", sa.Boolean(), nullable=True),
        sa.Column("has_extractable_text", sa.Boolean(), nullable=True),
        sa.Column("likely_scanned", sa.Boolean(), nullable=True),
        sa.Column("likely_image_only", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["file_id"], ["file.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("file_id"),
    )
    op.create_table(
        "review_flag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("resolution_note", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["file_id"], ["file.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("review_flag", schema=None) as batch_op:
        batch_op.create_index(
            "ix_review_flag_open_file_id",
            ["file_id"],
            unique=True,
            sqlite_where=sa.text("resolved_at IS NULL"),
        )

    op.create_table(
        "video_metadata",
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("has_audio", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["file_id"], ["file.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("file_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("video_metadata")
    with op.batch_alter_table("review_flag", schema=None) as batch_op:
        batch_op.drop_index(
            "ix_review_flag_open_file_id", sqlite_where=sa.text("resolved_at IS NULL")
        )

    op.drop_table("review_flag")
    op.drop_table("pdf_metadata")
    op.drop_table("mesh_metadata")
    with op.batch_alter_table("image_metadata", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_image_metadata_pixel_count"))

    op.drop_table("image_metadata")
    with op.batch_alter_table("file_text", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_file_text_issn"))
        batch_op.drop_index(batch_op.f("ix_file_text_isbn"))

    op.drop_table("file_text")
    op.drop_table("file_metadata")
    op.drop_table("file_llm_extraction")
    op.drop_table("error")
    op.drop_table("audio_metadata")
    with op.batch_alter_table("file", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_file_sha256"))
        batch_op.drop_index(batch_op.f("ix_file_root_id"))
        batch_op.drop_index(batch_op.f("ix_file_product_id"))
        batch_op.drop_index(batch_op.f("ix_file_media_type"))
        batch_op.drop_index(batch_op.f("ix_file_duplicate_of_id"))
        batch_op.drop_index(batch_op.f("ix_file_disposition"))

    op.drop_table("file")
    with op.batch_alter_table("product_line_alias", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_product_line_alias_product_line_id"))

    op.drop_table("product_line_alias")
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_product_product_line_id"))

    op.drop_table("product")
    with op.batch_alter_table("product_line", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_product_line_product_type_id"))

    op.drop_table("product_line")
    with op.batch_alter_table("root", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_root_kind"))

    op.drop_table("root")
    op.drop_table("product_type")
    # ### end Alembic commands ###
